### ISSUE TITLE
No way to declare types explicitly

### ISSUE THREAD

**Issue by mdg** [mdg/leema#23]
Sometimes we want to be explicit the type of a particular variable. Currently there's no way to do this. 

Expected: This should be possbile. Probably best to just use the Rust syntax for it with a colon and the type after the let's LHS. Like...
```
let empty: [Int] := []
```

**Comment by felixzhuologist** [comment]
how do you think that should work? would you add an `Option<Type>` to `Ast::Let` and then use that when typechecking?

**Comment by mdg** [comment]
this is done.
